// mockApi.js

export async function getAreas() {
  return [
    {
      id: "area-1",
      name: "Living Room",
      location_type: "indoor",
      is_covered: true,
      is_greenhouse: false,
      brightness: "medium",
    },
    {
      id: "area-2",
      name: "Front Garden",
      location_type: "outdoor",
      is_covered: false,
      is_greenhouse: false,
      brightness: "high",
    },
    {
      id: "area-3",
      name: "Greenhouse",
      location_type: "outdoor",
      is_covered: true,
      is_greenhouse: true,
      brightness: "high",
    },
  ];
}

export async function getPlots() {
  return [
    {
      id: "plot-1",
      name: "Tomato Bed",
      area_id: "area-2",
      plot_type: "raised_bed",
      width: 4,
      length: 2,
      soil_type: "loam",
      drainage_level: "good",
      ph: 6.8,
    },
    {
      id: "plot-2",
      name: "Herb Row",
      area_id: "area-3",
      plot_type: "row",
      width: 2,
      length: 4,
      soil_type: "sandy",
      drainage_level: "moderate",
      ph: 7.2,
    },
  ];
}

export async function getPlants() {
  return [
    {
      id: "plant-1",
      name: "Fiddle Leaf Fig",
      species_id: "planttype-1",
      potted: true,
      area_id: "area-1",
      plot_id: null,
      acquired_date: "2024-09-15",
      notes: "Getting brown tips on leaves.",
    },
    {
      id: "plant-2",
      name: "Tomato Plant A",
      species_id: "planttype-2",
      potted: false,
      area_id: null,
      plot_id: "plot-1",
      position: { x: 0, y: 0 },
      acquired_date: "2025-03-12",
      notes: "",
    },
    {
      id: "plant-2.1",
      name: "Tomato Plant B Plum",
      species_id: "planttype-2.1",
      potted: false,
      area_id: null,
      plot_id: "plot-1",
      position: { x: 0, y: 1 },
      acquired_date: "2025-03-12",
      notes: "",
    },
    {
      id: "plant-3",
      name: "Basil",
      species_id: "planttype-3",
      potted: true,
      area_id: "area-3",
      plot_id: null,
      acquired_date: "2025-05-01",
      notes: "Thriving in the greenhouse.",
    },
    {
      id: "plant-4",
      name: "Rosemary",
      species_id: "planttype-4",
      potted: true,
      area_id: "area-3",
      plot_id: null,
      acquired_date: "2025-05-10",
      notes: "",
    },
    {
      id: "plant-5",
      name: "Snake Plant",
      species_id: "planttype-5",
      potted: true,
      area_id: "area-1",
      plot_id: null,
      acquired_date: "2024-11-20",
      notes: "Low maintenance.",
    },
    {
      id: "plant-6",
      name: "Mint",
      species_id: "planttype-6",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 0 , y: 0 },
      acquired_date: "2025-04-15",
      notes: "",
    },
    {
      id: "plant-7",
      name: "Lavender",
      species_id: "planttype-7",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 1, y: 0 },
      acquired_date: "2025-04-18",
      notes: "",
    },
    {
      id: "plant-8",
      name: "Cucumber",
      species_id: "planttype-2",
      potted: false,
      area_id: null,
      plot_id: "plot-1",
      position: { x: 1, y: 0 },
      acquired_date: "2025-03-20",
      notes: "",
    },
    {
      id: "plant-9",
      name: "Parsley",
      species_id: "planttype-3",
      potted: true,
      area_id: "area-3",
      plot_id: null,
      acquired_date: "2025-05-05",
      notes: "",
    },
    {
      id: "plant-10",
      name: "Spider Plant",
      species_id: "planttype-5",
      potted: true,
      area_id: "area-1",
      plot_id: null,
      acquired_date: "2024-12-01",
      notes: "",
    },
    {
      id: "plant-11",
      name: "Oregano",
      species_id: "planttype-6",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 0, y: 1 },
      acquired_date: "2025-04-22",
      notes: "",
    },
    {
      id: "plant-12",
      name: "Thyme",
      species_id: "planttype-4",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 1, y: 1 },
      acquired_date: "2025-04-25",
      notes: "",
    },
    {
      id: "plant-13",
      name: "Aloe Vera",
      species_id: "planttype-5",
      potted: true,
      area_id: "area-1",
      plot_id: null,
      acquired_date: "2024-10-10",
      notes: "",
    },
    {
      id: "plant-14",
      name: "Cherry Tomato C",
      species_id: "planttype-2",
      potted: false,
      area_id: null,
      plot_id: "plot-1",
      position: { x: 1, y: 1 },
      acquired_date: "2025-03-14",
      notes: "",
    },
    {
      id: "plant-15",
      name: "Plum Tomato D",
      species_id: "planttype-2.1",
      potted: false,
      area_id: null,
      plot_id: "plot-1",
      position: { x: 2, y: 0 },
      acquired_date: "2025-03-16",
      notes: "",
    },
    {
      id: "plant-16",
      name: "Basil B",
      species_id: "planttype-3",
      potted: true,
      area_id: "area-3",
      plot_id: null,
      acquired_date: "2025-05-03",
      notes: "",
    },
    {
      id: "plant-17",
      name: "Rosemary B",
      species_id: "planttype-4",
      potted: true,
      area_id: "area-3",
      plot_id: null,
      acquired_date: "2025-05-12",
      notes: "",
    },
    {
      id: "plant-18",
      name: "Mint B",
      species_id: "planttype-6",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 0, y: 2 },
      acquired_date: "2025-04-17",
      notes: "",
    },
    {
      id: "plant-19",
      name: "Lavender B",
      species_id: "planttype-7",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 1, y: 2 },
      acquired_date: "2025-04-19",
      notes: "",
    },
    {
      id: "plant-20",
      name: "Cucumber B",
      species_id: "planttype-2",
      potted: false,
      area_id: null,
      plot_id: "plot-1",
      position: { x: 2, y: 1 },
      acquired_date: "2025-03-21",
      notes: "",
    },
    {
      id: "plant-21",
      name: "Parsley B",
      species_id: "planttype-3",
      potted: true,
      area_id: "area-3",
      plot_id: null,
      acquired_date: "2025-05-06",
      notes: "",
    },
    {
      id: "plant-22",
      name: "Spider Plant B",
      species_id: "planttype-5",
      potted: true,
      area_id: "area-1",
      plot_id: null,
      acquired_date: "2024-12-02",
      notes: "",
    },
    {
      id: "plant-23",
      name: "Oregano B",
      species_id: "planttype-6",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 0, y: 3 },
      acquired_date: "2025-04-23",
      notes: "",
    },
    {
      id: "plant-24",
      name: "Thyme B",
      species_id: "planttype-4",
      potted: false,
      area_id: null,
      plot_id: "plot-2",
      position: { x: 1, y: 3 },
      acquired_date: "2025-04-26",
      notes: "",
    },
  ];
}

export async function getPlantTypes() {
  return [
    {
      id: "planttype-1",
      common_name: "Fiddle Leaf Fig",
      latin_name: "Ficus lyrata",
      care_profile: {
        light: "bright indirect",
        water: "weekly",
        soil: "well-draining",
      },
      image_url: "https://example.com/fiddle-leaf.jpg",
      is_edible: false,
    },
    {
      id: "planttype-2",
      common_name: "Cherry Tomato",
      latin_name: "Solanum lycopersicum",
      care_profile: {
        light: "full sun",
        water: "2-3x weekly",
        soil: "rich, well-draining",
      },
      image_url: "https://example.com/tomato.jpg",
      is_edible: true,
    },
    {
      id: "planttype-2.1",
      common_name: "Plum Tomato",
      latin_name: "Solanum lycopersicpluum",
      care_profile: {
        light: "partial sun",
        water: "2-3x weekly",
        soil: "rich, well-draining",
      },
      image_url: "https://example.com/tomato.jpg",
      is_edible: true,
    },
    {
      id: "planttype-3",
      common_name: "Basil",
      latin_name: "Ocimum basilicum",
      care_profile: {
        light: "full sun",
        water: "frequent",
        soil: "light, moist",
      },
      image_url: "https://example.com/basil.jpg",
      is_edible: true,
    },
    {
      id: "planttype-4",
      common_name: "Rosemary",
      latin_name: "Salvia rosmarinus",
      care_profile: {
        light: "full sun",
        water: "weekly",
        soil: "well-draining",
      },
      image_url: "https://example.com/rosemary.jpg",
      is_edible: true,
    },
    {
      id: "planttype-5",
      common_name: "Snake Plant",
      latin_name: "Sansevieria trifasciata",
      care_profile: {
        light: "low to bright indirect",
        water: "monthly",
        soil: "well-draining",
      },
      image_url: "https://example.com/snakeplant.jpg",
      is_edible: false,
    },
    {
      id: "planttype-6",
      common_name: "Mint",
      latin_name: "Mentha",
      care_profile: {
        light: "partial sun",
        water: "frequent",
        soil: "moist, rich",
      },
      image_url: "https://example.com/mint.jpg",
      is_edible: true,
    },
    {
      id: "planttype-7",
      common_name: "Lavender",
      latin_name: "Lavandula",
      care_profile: {
        light: "full sun",
        water: "weekly",
        soil: "well-draining, sandy",
      },
      image_url: "https://example.com/lavender.jpg",
      is_edible: false,
    },
  ];
}
